# SCREEN
SCREEN_HEIGHT = 800
SCREEN_WIDTH = 600
SCREEN_IMAGE = "assets/background.png"

# BIRD
BIRD_IMAGE = "assets/bird.png"
BIRD_SPEED = 9
BIRD_ACCELERATION = 1

# FLOOR
FLOOR_IMAGE = "assets/floor.png"
FLOOR_WIDTH = SCREEN_WIDTH * 2
FLOOR_HEIGHT = SCREEN_HEIGHT // 8
FLOOR_SPEED = BIRD_SPEED

# PIPE 
PIPE_IMAGE = "assets/pipe.png"
PIPE_WIDTH = SCREEN_WIDTH//10
PIPE_HEIGHT = SCREEN_HEIGHT//2
PIPE_GAP = 120
PIPE_SPEED = FLOOR_SPEED
PIPE_HEIGHT_MIN = 200
PIPE_HEIGHT_MAX = 400

# GAME 
GAME_FPS = 30
